services:
  testbed:
    restart: on-failure
    init: true
    build:
      context: .
      dockerfile: testbed/Dockerfile

  firingrange:
    restart: on-failure
    init: true
    image: 0xshyam/firingrange:10
    logging:
      driver: none

  runner:
    init: true
    environment:
      - NO_SANDBOX=${NO_SANDBOX:-0}
      - TESTBED_URL=http://testbed:8080
      - REMOTE_SCRIPT_URL=http://testbed:8080/xss.js
      - RUN_IDENTIFIER=${RUN_IDENTIFIER}
    build:
      context: .
      args:
      - USERID=${USERID}
      - GROUPID=${GROUPID}
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/data
    depends_on:
      - testbed
    links:
      - testbed
      - firingrange
    command: ${COMMAND:-"polytest.ts /usr/src/data/example.json /usr/src/data/polytest"}
